services:
  hotelristorantepuntoverde-it:
    image: hotelristorantepuntoverde-it
    container_name: hotelristorantepuntoverde-it
    env_file: ".env"
    build: .
    networks:
      - network
    expose:
      - 3000
    restart: always

networks:
  network: